import json
import os
import sys
from typing import List, Dict, Any

# ==========================================
# CONFIGURATION
# ==========================================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Ensure these paths match where your server saves the files
MENU_FILE = os.path.join(BASE_DIR, "food", "MythosMenu.json")
# New file for dynamic recommendations generated by Admin Panel
RECS_FILE = os.path.join(BASE_DIR, "food", "recommendations.json")

# ==========================================
# HELPER FUNCTIONS
# ==========================================
def normalize_name(s: str) -> str:
    """
    Convert item names to a normalized key for matching:
    - lowercased
    - spaces/underscores -> hyphens
    - strips special chars like & if needed
    """
    return (
        str(s or "")
        .strip()
        .lower()
        .replace(" ", "-")
        .replace("_", "-")
    )

def load_json_file(filepath: str) -> Any:
    """Generic JSON loader."""
    if not os.path.exists(filepath):
        return [] if "recommendations" in filepath else {}
        
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        sys.stderr.write(f"[pop_recommend] Failed to load {filepath}: {e}\n")
        return [] if "recommendations" in filepath else {}

def collect_menu_items(data: Any) -> List[Dict[str, Any]]:
    """Flatten nested menu JSON into a simple list of item dicts."""
    items: List[Dict[str, Any]] = []

    def walk(node: Any):
        if node is None:
            return
        if isinstance(node, list):
            for x in node:
                walk(x)
            return
        if isinstance(node, dict):
            # Check for 'items' array
            if isinstance(node.get("items"), list):
                for i in node["items"]:
                    if isinstance(i, dict) and i.get("visible", True) is not False:
                        items.append(i)
            # Recurse
            for k, v in node.items():
                if k not in ("items", "visible") and isinstance(v, (list, dict)):
                    walk(v)

    walk(data)
    return items

# ==========================================
# INITIALIZATION & DYNAMIC RULE BUILDING
# ==========================================

# 1. Load Data
MENU_DATA = load_json_file(MENU_FILE)
RECS_DATA = load_json_file(RECS_FILE) # Expecting list of groups: [{items: [], description: ""}, ...]

ALL_ITEMS = collect_menu_items(MENU_DATA)

# 2. Create a Menu Index: { "normalized-name": {item_data} }
MENU_INDEX: Dict[str, Dict[str, Any]] = {
    normalize_name(item.get("name", "")): item
    for item in ALL_ITEMS
}

# 3. Build Pairing Rules Dynamically
# Logic: If items [A, B, C] are in a recommendation group:
# A implies -> [B, C]
# B implies -> [A, C]
# C implies -> [A, B]
PAIRING_RULES: Dict[str, List[str]] = {}

if isinstance(RECS_DATA, list):
    for group in RECS_DATA:
        group_items = group.get("items", [])
        if not group_items or len(group_items) < 2:
            continue
            
        # Get all normalized names in this group
        group_names = [item.get("name", "") for item in group_items]
        
        # Create associations (Cross-referencing)
        for current_item in group_names:
            norm_current = normalize_name(current_item)
            
            # Initialize list if not exists
            if norm_current not in PAIRING_RULES:
                PAIRING_RULES[norm_current] = []
            
            # Add all OTHER items in this group as targets
            for other_item in group_names:
                if other_item == current_item:
                    continue
                
                # Avoid duplicates in the list
                if other_item not in PAIRING_RULES[norm_current]:
                    PAIRING_RULES[norm_current].append(other_item)

# ==========================================
# LOGIC
# ==========================================
def recommend_for_cart(cart_items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Returns recommended add-on items based on dynamic rules.
    """
    if not cart_items:
        return []

    # 1. Create a set of normalized names currently in the cart for easy checking
    cart_norm_names = {normalize_name(i.get("name")) for i in cart_items}
    
    recommendations: List[Dict[str, Any]] = []
    already_suggested = set()

    for cart_item in cart_items:
        main_name = cart_item.get("name", "")
        main_norm = normalize_name(main_name)
        
        # Get the list of potential targets (pairing rules) for this item
        targets = PAIRING_RULES.get(main_norm)
        if not targets:
            continue

        # --- EXCLUSIVITY LOGIC ---
        # If the cart ALREADY contains one of the pairings for this item,
        # skip suggesting the others to avoid spamming the user.
        target_norms = [normalize_name(t) for t in targets]
        
        if not set(target_norms).isdisjoint(cart_norm_names):
            continue
        # -------------------------

        for t_name in targets:
            t_norm = normalize_name(t_name)
            
            # Skip if already in cart
            if t_norm in cart_norm_names:
                continue
            
            # Skip if already suggested in this result set
            if t_norm in already_suggested:
                continue

            # Look up full details in the Menu Index
            menu_item = MENU_INDEX.get(t_norm)
            if not menu_item:
                continue

            already_suggested.add(t_norm)

            # Build the recommendation object
            rec = {
                "name": menu_item.get("name", ""),
                "price": float(menu_item.get("price", 0) or 0),
                "description": menu_item.get("description", ""),
                "allergens": menu_item.get("allergens", ""),
                "calories": menu_item.get("calories", ""),
                "img": menu_item.get("img") or None,
                "video": menu_item.get("video") or None,
                "spice": menu_item.get("spice", ""),
                "source_title": f"Pairs with {main_name}", # Helpful context
            }
            recommendations.append(rec)

    # --- SORTING LOGIC ---
    # Sort by price descending (Upsell: High -> Low)
    recommendations.sort(key=lambda x: x["price"], reverse=True)
    
    return recommendations

# ==========================================
# MAIN EXECUTION (Called by Node.js)
# ==========================================
if __name__ == "__main__":
    try:
        # Read JSON input from stdin
        # Using sys.stdin.buffer.read() and decoding manually is safer for UTF-8 in some envs
        raw_input = sys.stdin.read()
        
        if not raw_input.strip():
            print("[]")
            sys.exit(0)
            
        data = json.loads(raw_input)
        cart_data = data.get("cart", [])
        
        # Get Recommendations
        recs = recommend_for_cart(cart_data)
        
        # Print Result as JSON string
        print(json.dumps(recs, ensure_ascii=False))
        
    except Exception as e:
        # Print empty list on error so frontend doesn't crash
        sys.stderr.write(f"Error: {e}\n")
        print("[]")