export const BASE_PATH = '/Trump';
export const API_PREFIX = '/Trump';
export const RESTAURANT_ID = 'trump';
export const SOCKET_PATH = '/Trump/socket.io';

export const ENDPOINTS = {
  menu: `${API_PREFIX}/api/menu`,
  deals: `${API_PREFIX}/api/deals`,
  recommend: `${API_PREFIX}/api/recommend`,
  chat: `${API_PREFIX}/api/chat`,
  config: `${API_PREFIX}/api/config`,
  aiPairing: `${API_PREFIX}/api/ai-pairing`,
  submitOrder: `${API_PREFIX}/submit_order`,
  authMe: `${API_PREFIX}/api/auth/me`,
  authLogin: `${API_PREFIX}/api/auth/login`,
  authLogout: `${API_PREFIX}/api/auth/logout`,
  authAccounts: `${API_PREFIX}/api/auth/accounts`,
  orders: `${API_PREFIX}/orders`,
  history: `${API_PREFIX}/history`,
  complete: `${API_PREFIX}/complete`,
  incomplete: `${API_PREFIX}/incomplete`,
  upload: `${API_PREFIX}/api/upload`,
  waiterTableStatus: (tableId: string) => `${API_PREFIX}/api/waiter/table/${tableId}/status`,
  waiterAddItems: `${API_PREFIX}/api/waiter/add-items`,
  waiterArchiveTable: `${API_PREFIX}/api/waiter/archive-table`,
  menuAdminItems: `${API_PREFIX}/api/menu/items`,
  menuCategories: `${API_PREFIX}/api/menu/categories`,
  menuItemAvailability: (id: number) => `${API_PREFIX}/api/menu/items/${id}/availability`,
  menuItemMedia: (id: number) => `${API_PREFIX}/api/menu/items/${id}/media`,
  menuItemUpdate: (id: number) => `${API_PREFIX}/api/menu/items/${id}`,
  menuItemDelete: (id: number) => `${API_PREFIX}/api/menu/items/${id}`,
  menuItemBulk: `${API_PREFIX}/api/menu/items/bulk`,
  chefRecs: `${API_PREFIX}/api/menu/chef-recs`,
  chefRec: (id: number) => `${API_PREFIX}/api/menu/chef-recs/${id}`,
  bundles: `${API_PREFIX}/api/menu/bundles`,
  bundlesAdmin: `${API_PREFIX}/api/menu/bundles/admin`,
  bundle: (id: number) => `${API_PREFIX}/api/menu/bundles/${id}`,
  kitchenOrders: `${API_PREFIX}/api/kitchen/orders`,
  kitchenUpdateStatus: (id: number) => `${API_PREFIX}/api/kitchen/orders/${id}/status`,
  analyticsummary: `${API_PREFIX}/api/analytics/summary`,
  analyticsItems: `${API_PREFIX}/api/analytics/items`,
  analyticsTables: `${API_PREFIX}/api/analytics/tables`,
  analyticsHours: `${API_PREFIX}/api/analytics/hours`,
  analyticsTrend: `${API_PREFIX}/api/analytics/trend`,
  analyticsDayOfWeek: `${API_PREFIX}/api/analytics/day-of-week`,
  analyticsPairings: `${API_PREFIX}/api/analytics/pairings`,
  analyticsJourney: `${API_PREFIX}/api/analytics/journey`,
  analyticsRecommendations: `${API_PREFIX}/api/analytics/recommendations`,
  analyticsRecommendationsInsights: `${API_PREFIX}/api/analytics/recommendations/insights`,
  recoEvents: `${API_PREFIX}/api/reco/events`,
  adminTableCarts: `${API_PREFIX}/api/admin/tables/carts`,
  reservations: `${API_PREFIX}/api/reservations`,
  ratings: `${API_PREFIX}/api/ratings`,
  pushVapidKey: `${API_PREFIX}/api/push/vapid-key`,
  pushSubscribe: `${API_PREFIX}/api/push/subscribe`,
  // Waiter-AI app
  floor: `${API_PREFIX}/api/floor`,
  tableIntel: (tableId: string) => `${API_PREFIX}/api/waiter/table/${tableId}/intel`,
  coach: `${API_PREFIX}/api/waiter/coach`,
  cartRecommendations: `${API_PREFIX}/api/waiter/cart-recommendations`,
  orderedTogether: `${API_PREFIX}/api/waiter/ordered-together`,
  sommelier: `${API_PREFIX}/api/sommelier`,
  ask: `${API_PREFIX}/api/ask`,
  recovery: `${API_PREFIX}/api/waiter/recovery`,
  upsellEvent: `${API_PREFIX}/api/upsell-event`,
  waiterPerformance: `${API_PREFIX}/api/waiter/me/performance`,
  waiterShiftReport: `${API_PREFIX}/api/waiter/me/shift-report`,
  waiterLeaderboard: `${API_PREFIX}/api/waiter/leaderboard`,
  guests: `${API_PREFIX}/api/guests`,
  guest: (id: number) => `${API_PREFIX}/api/guests/${id}`,
  seatGuest: (tableId: string) => `${API_PREFIX}/api/waiter/table/${tableId}/seat-guest`,
  tableCovers: (tableId: string) => `${API_PREFIX}/api/waiter/table/${tableId}/covers`,
  completeTable: (tableId: string) => `${API_PREFIX}/api/waiter/table/${tableId}/complete`,
  nlgStatus: `${API_PREFIX}/api/waiter/nlg-status`,
  waiterTasks: `${API_PREFIX}/api/waiter/tasks`,
  waiterTaskAck: (id: number | string) => `${API_PREFIX}/api/waiter/tasks/${id}/ack`,
  waiterTaskResolve: (id: number | string) => `${API_PREFIX}/api/waiter/tasks/${id}/resolve`,
  waiterChatCenter: `${API_PREFIX}/api/waiter/chat-center`,
  waiterChatAnalysis: `${API_PREFIX}/api/waiter/chat-analysis`,
  waiterBirthdayRequest: `${API_PREFIX}/api/waiter/birthday-request`,
  waiterBirthdayApproval: (id: number | string) => `${API_PREFIX}/api/waiter/birthday-approval/${id}`,
  // Phase 03 — staff operations (shifts, ownership, notifications, owner ops, audit)
  shiftMe: `${API_PREFIX}/api/shift/me`,
  shiftStart: `${API_PREFIX}/api/shift/start`,
  shiftEnd: `${API_PREFIX}/api/shift/end`,
  shifts: `${API_PREFIX}/api/shifts`,
  shiftsHistory: `${API_PREFIX}/api/shifts/history`,
  shiftForceEnd: (username: string) => `${API_PREFIX}/api/shifts/${username}/end`,
  ownership: `${API_PREFIX}/api/ownership`,
  ownershipTable: (tableId: string) => `${API_PREFIX}/api/ownership/${tableId}`,
  ownershipHistory: (tableId: string) => `${API_PREFIX}/api/ownership/${tableId}/history`,
  ownershipAssign: (tableId: string) => `${API_PREFIX}/api/ownership/${tableId}/assign`,
  ownershipTransfer: (tableId: string) => `${API_PREFIX}/api/ownership/${tableId}/transfer`,
  ownershipTakeover: (tableId: string) => `${API_PREFIX}/api/ownership/${tableId}/takeover`,
  ownershipReassign: (tableId: string) => `${API_PREFIX}/api/ownership/${tableId}/reassign`,
  notifications: `${API_PREFIX}/api/notifications`,
  notificationsUnread: `${API_PREFIX}/api/notifications/unread-count`,
  notificationAck: (id: number | string) => `${API_PREFIX}/api/notifications/${id}/ack`,
  notificationsAckAll: `${API_PREFIX}/api/notifications/ack-all`,
  ownerOperations: `${API_PREFIX}/api/owner/operations`,
  auditTrail: `${API_PREFIX}/api/audit`,
} as const;
