export const BASE_PATH = '/Trump';
export const API_PREFIX = '/Trump';
export const RESTAURANT_ID = 'trump';
export const SOCKET_PATH = '/Trump/socket.io';

export const ENDPOINTS = {
  menu: `${API_PREFIX}/api/menu`,
  deals: `${API_PREFIX}/api/deals`,
  recommend: `${API_PREFIX}/api/recommend`,
  chat: `${API_PREFIX}/api/chat`,
  aiPairing: `${API_PREFIX}/api/ai-pairing`,
  submitOrder: `${API_PREFIX}/submit_order`,
  authMe: `${API_PREFIX}/api/auth/me`,
  authLogin: `${API_PREFIX}/api/auth/login`,
  authLogout: `${API_PREFIX}/api/auth/logout`,
  authAccounts: `${API_PREFIX}/api/auth/accounts`,
  orders: `${API_PREFIX}/orders`,
  history: `${API_PREFIX}/history`,
  complete: `${API_PREFIX}/complete`,
  incomplete: `${API_PREFIX}/incomplete`,
  upload: `${API_PREFIX}/api/upload`,
  waiterTableStatus: (tableId: string) => `${API_PREFIX}/api/waiter/table/${tableId}/status`,
  waiterAddItems: `${API_PREFIX}/api/waiter/add-items`,
  waiterArchiveTable: `${API_PREFIX}/api/waiter/archive-table`,
  menuAdminItems: `${API_PREFIX}/api/menu/items`,
  menuCategories: `${API_PREFIX}/api/menu/categories`,
  menuItemAvailability: (id: number) => `${API_PREFIX}/api/menu/items/${id}/availability`,
  menuItemMedia: (id: number) => `${API_PREFIX}/api/menu/items/${id}/media`,
  menuItemDelete: (id: number) => `${API_PREFIX}/api/menu/items/${id}`,
  menuItemBulk: `${API_PREFIX}/api/menu/items/bulk`,
  kitchenOrders: `${API_PREFIX}/api/kitchen/orders`,
  kitchenUpdateStatus: (id: number) => `${API_PREFIX}/api/kitchen/orders/${id}/status`,
  analyticsummary: `${API_PREFIX}/api/analytics/summary`,
  analyticsItems: `${API_PREFIX}/api/analytics/items`,
  analyticsTables: `${API_PREFIX}/api/analytics/tables`,
  analyticsHours: `${API_PREFIX}/api/analytics/hours`,
  adminTableCarts: `${API_PREFIX}/api/admin/tables/carts`,
  reservations: `${API_PREFIX}/api/reservations`,
  ratings: `${API_PREFIX}/api/ratings`,
  pushVapidKey: `${API_PREFIX}/api/push/vapid-key`,
  pushSubscribe: `${API_PREFIX}/api/push/subscribe`,
  // Waiter-AI app
  floor: `${API_PREFIX}/api/floor`,
  tableIntel: (tableId: string) => `${API_PREFIX}/api/waiter/table/${tableId}/intel`,
  coach: `${API_PREFIX}/api/waiter/coach`,
  sommelier: `${API_PREFIX}/api/sommelier`,
  ask: `${API_PREFIX}/api/ask`,
  recovery: `${API_PREFIX}/api/waiter/recovery`,
  upsellEvent: `${API_PREFIX}/api/upsell-event`,
  waiterPerformance: `${API_PREFIX}/api/waiter/me/performance`,
  waiterShiftReport: `${API_PREFIX}/api/waiter/me/shift-report`,
  waiterLeaderboard: `${API_PREFIX}/api/waiter/leaderboard`,
  guests: `${API_PREFIX}/api/guests`,
  guest: (id: number) => `${API_PREFIX}/api/guests/${id}`,
  seatGuest: (tableId: string) => `${API_PREFIX}/api/waiter/table/${tableId}/seat-guest`,
  nlgStatus: `${API_PREFIX}/api/waiter/nlg-status`,
} as const;
